language: cpp

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install g++-4.8 libgtest-dev -qq
    - export CXX="g++-4.8"
    - pushd /usr/src/gtest
    - sudo cmake .
    - sudo cmake --build .
    - sudo cp libgtest* /usr/lib
    - popd

script:
    - cmake .
    - cmake --build .
    - ./unittest
